### ISSUE TITLE
Only load devTools if local server is 'up'

### ISSUE THREAD

**Issue by vetm73** [zalmoxisus/remote-redux-devtools#30]
I would like to add devTools to the store *only* if the local server is up. Because this is an async operation I end up with an 'incomplete' store.

The async function which checks if the server is there:

```javascript
export async function isReduxDevServerAlive(url,port, secure = false) {
    const server = secure ? 'https' : 'http' + `://${url}:${port}`;
    try {
        let response = await fetch(server);
        return true;
    } catch(error) {
        return false;
    }
}
```

The `store.js` script

```javascript
import thunk from 'redux-thunk';
import devTools from 'remote-redux-devtools';
import { isReduxDevServerAlive } from './util/dev'
import { createStore, applyMiddleware, combineReducers, compose } from 'redux';

import * as reducers from './reducers';
import * as constants from './constants';

let composable = [ applyMiddleware(thunk) ];
const reducer = combineReducers(reducers);

if(isReduxDevServerAlive(constants.REDUX_DEV_SERVER, constants.REDUX_DEV_SERVER_PORT))
{
    composable.push(
        devTools({
            name: 'EPP app', realtime: true,
            hostname: constants.REDUX_DEV_SERVER, port: constants.REDUX_DEV_SERVER_PORT,
            maxAge: 30, filters: {blacklist: ['EFFECT_RESOLVED']}
        })
    );
}

const bconfigureStore = (c) => {
        return createStore(reducer,{},compose(...c));
}

export default function configureStore() {
    return bconfigureStore(composable);
}
``` 
The script should wait to export till when it knows if the server is up or down. Could you help me out how to accomplish this?

**Comment by zalmoxisus** [comment]
You have just to make your `configureStore` function asynchronous and apply the render in a callback, for example, as we're doing [here](https://github.com/zalmoxisus/crossbuilder/blob/master/src/app/index.js).

However, you could just set `realtime` to `false` and have an action to start monitoring, specified for `startOn` parameter (which you dispatch explicitly or if local server is 'up'). In this case you will not have to restart the application in order to start monitoring. The only downside is that [`redux-devtools-instrument`](https://github.com/zalmoxisus/redux-devtools-instrument) will still store the history, it doesn't affect the performance significantly, but can consume RAM in case you have large objects in the states. We could add the ability to start/stop instrumentation there.

**Comment by vetm73** [comment]
Tnx for your help and example. Helped me a lot!
